language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/de0569306a16f2435ef2
    on_success: change
    on_failure: always
    on_start: false

env:
  - APM_TEST_PACKAGES=build

before_script:
  - npm install

script:
  - npm test

git:
  depth: 10
